import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Archivo } from "next/font/google";
import "./globals.css";
import { Layout } from "@/component/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Familia de marca. El manual (5.5) especifica Gotham, que es de Hoefler&Co y
// requiere licencia comercial — no esta en el proyecto. Montserrat es geometrica
// y comparte la construccion de circulo y cuadrado que describe 5.1, asi que
// sostiene la jerarquia sin romper la identidad. Al comprar Gotham se reemplaza
// aca y todo el sistema (src/libs/brand.ts) lo hereda.
const brandSans = Montserrat({
  variable: "--font-brand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

// Kiosco 2026: el diseño se apoya en Archivo, sobre todo en su italic 900 para
// los titulares. Sin ella los titulares pierden la inclinación y el peso.
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sweepstouch | Tablets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${brandSans.variable} ${archivo.variable} ${geistMono.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

